export enum MpdCommand {
  // status
  Ping = 'ping',
  ClearError = 'clearerror',
  Status = 'status',
  CurrentSong = 'currentsong',
  Stats = 'stats',
  // playback options
  Consume = 'consume',
  Crossfade = 'crossfade',
  MixrampDb = 'mixrampdb',
  MixrampDelay = 'mixrampdelay',
  Random = 'random',
  Repeat = 'repeat',
  Single = 'single',
  ReplayGainMode = 'replay_gain_mode ',
  ReplayGainStatus = 'replay_gain_status',
  GetVolume = 'getvol',
  SetVolume = 'setvol',
  // controlling playback
  Next = 'next',
  Pause = 'pause',
  Play = 'play',
  PlayId = 'playid',
  Previous = 'previous',
  Seek = 'seek',
  SeekId = 'seekid',
  SeekCur = 'seekcur',
  Stop = 'stop',
}
